### ISSUE TITLE
Cannot run examples

### ISSUE THREAD

**Issue by mikebelanger** [pex-gl/pex-gltf#1]
Hi,

This Plex stuff looks pretty neat, and I'm stoked on running the example.   But it doesn't look like npm can find the latest gltf package.  If this is just because the package's url has been recently updated, then please ignore this silly question.  Otherwise, here is the error code npm returns:

> npm install pex-gltf --save
> 
>  ERR! Darwin 15.4.0
> npm ERR! argv "/usr/local/Cellar/node/5.10.1/bin/node" "/usr/local/bin/npm" "install" "pex-gltf" "--save"
> npm ERR! node v5.10.1
> npm ERR! npm  v3.8.3
> npm ERR! code E404
> 
> npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/pex-gltf
> npm ERR! 404
> npm ERR! 404  'pex-gltf' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.

**Comment by vorg** [comment]
Hi @mikebelanger `pex-gltf` is not ready to be published on npm but could you try to run the examples as follows (on OSX and probably Linux).

``` bash
#download pex-gltf code and examples
git clone https://github.com/pex-gl/pex-gltf

#install dependencies
cd pex-gltf 
npm install

#download sample glTF meshes
cd pex-gltf/example
git clone https://github.com/KhronosGroup/glTF
```

And now to run `example/basic`

``` bash
cd basic
npm install
npm run build
#we need to load files from the server otherwise AJAX calls to glTF files will faile
cd ..
python -m SimpleHTTPServer 
```

and open [http://localhost:8000/basic/](http://localhost:8000/basic/) in your browser

Same steps to run `example/all`

**Comment by mikebelanger** [comment]
Ah ok, yeah those instructions work!  Obviously I need to brush up on how to build these sorts node projects.  Thanks!
